version: 2

multi-ecosystem-groups:
  dependencies:
    assignees:
      - BrailleBennett
    schedule:
      interval: weekly
      day: sunday

updates:
  - package-ecosystem: github-actions
    directory: "/"
    patterns: [ "*" ]
    multi-ecosystem-group: dependencies

  - package-ecosystem: gradle
    directory: "/"
    patterns: [ "*" ]
    multi-ecosystem-group: dependencies