version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    groups:
      gh-actions:
        update-types:
          - minor
          - patch

  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    groups:
      gradle-dependencies:
        patterns:
          # Use wildcard to bundle plugins and libs into one PR
          - "*"
